//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.JNG.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.JNG.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad:.
        /// </summary>
        internal static string MainView_City {
            get {
                return ResourceManager.GetString("MainView_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1º Apellido:.
        /// </summary>
        internal static string MainView_FirstSurname {
            get {
                return ResourceManager.GetString("MainView_FirstSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar.
        /// </summary>
        internal static string MainView_GenerateButton {
            get {
                return ResourceManager.GetString("MainView_GenerateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método.
        /// </summary>
        internal static string MainView_Method {
            get {
                return ResourceManager.GetString("MainView_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        internal static string MainView_Name {
            get {
                return ResourceManager.GetString("MainView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        internal static string MainView_PlaceholderCity {
            get {
                return ResourceManager.GetString("MainView_PlaceholderCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        internal static string MainView_PlaceholderFirstSurname {
            get {
                return ResourceManager.GetString("MainView_PlaceholderFirstSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string MainView_PlaceholderName {
            get {
                return ResourceManager.GetString("MainView_PlaceholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        internal static string MainView_PlaceholderSecondSurname {
            get {
                return ResourceManager.GetString("MainView_PlaceholderSecondSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Jedi:.
        /// </summary>
        internal static string MainView_ResultName {
            get {
                return ResourceManager.GetString("MainView_ResultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2º Apellido:.
        /// </summary>
        internal static string MainView_SecondSurname {
            get {
                return ResourceManager.GetString("MainView_SecondSurname", resourceCulture);
            }
        }
    }
}
